package com.camel.drools.expert.sample.testbug1

import mock.com.camel.drools.expert.sample.service.domain.Order;
import mock.com.camel.drools.expert.sample.service.domain.RuleConditionSdo;

rule "order flow"
when
    $rcs:RuleConditionSdo($rc:ruleCondition)
    $order:Order(price>$rc.getDouble("minPrice"), source==$rc.getString("source"), dest==$rc.getString("dest"))
then
    System.out.println("finished rule for bug test 1" + $rc.getString("source"));
end